### PR TITLE
feat: Impl. New Icon

### PR DESCRIPTION
**Pull request by raditzlawliet**
- [x] Implement new logo on web title
- [x] Implement new logo on favicon

### CODE REVIEW

**Comment by muktihari** [comment]
image

Can you make the text a little bit below? Or just use [openivity-header.svg](https://github.com/openivity/openivity.github.io/blob/master/docs/images/openivity-header.svg)

**Comment by raditzlawliet** [comment]
@muktihari I think it is relate with browser,
from Chrome on Windows it show like this and have a good center
image

and below is the original svg header
image

my suggestion is using svg. 
The icon in svg header also not transparent yet, therefore we need to modified the svg first.

**Comment by muktihari** [comment]
I see, ok use the svg version for more consistent layout. I can only make the rectangle transparent: [logo.zip](https://github.com/user-attachments/files/15610284/logo.zip)

logo

openivity-header

**Comment by raditzlawliet** [comment]
Nice, thanks for the new svg. 
it looks nice.

image

**Review by muktihari — APPROVED** [review]

**Pull request merged**
