### PR TITLE
fix (#62): tool's trim/conceal negative distance

### LINKED ISSUE #62: Minor bug on tools slider got negative value
Expected value should be positive, got negative:

Screen Shot 2023-12-02 at 14 58 04

### PR DESCRIPTION
**Pull request by muktihari**
fix #62

image

### CODE REVIEW

**Review by raditzlawliet — APPROVED** [review]
lgtm, but there's another issue (i put here before create an issue is it relate with this or not)
- Open `Morning_Ride.fit` > Try to edit > Trim
- Open `Morning_Run.fit` > Try to edit > Trim > error
image
https://github.com/openivity/openivity.github.io/assets/3763178/27551356-b828-4022-9a93-ec7abe219f93
I think you already have the file so you can try it out

**Comment by raditzlawliet** [comment]
Oh wait, I try using one of your file is it `Mat..Loop.fit` having 0.01 at start
image

My personal fit looks good, no problem for now

**Comment by muktihari** [comment]
> lgtm, but there's another issue (i put here before create an issue is it relate with this or not)

how can this be reproduce? Is this issue persist after refreshing the browser-tab?  i tried in my local but it seems fine.

https://github.com/openivity/openivity.github.io/assets/15964188/0cf5906c-3ca2-48de-9383-5877b221bca8

> Oh wait, I try using one Mat..Loop.fit having 0.01 at start (i think you also already have this file)

Ah right, I will push the update after this

**Comment by muktihari** [comment]
> Open Morning_Run.fit > Try to edit > Trim > error

I think I know the cause, before we point to the problem, let me explain the full context:
In Session, there are Fields: `start_time` and `total_elapsed_time`,  these fields are used to group which record is belong to this session. From these fields, we get `EndTime = start_time + total_elapsed_time`, so any `record.Timestamp` between `StartTime` and `EndTime` will be included in this session. 

However, how `total_elapsed_time` in fit files retrieved from Strava is not calculated as we expected, example:
- Session: start_time: "1056157392",  total_elapsed_time: "2866.0", we get `EndTime = 1056160258`. We expect the last record will have timestamp "1056160258", but we got one record that has "1056160259", so there is one record that's not included in the session. And for records that not included in session, we create new session to accommodate that record (this to accommodate truncated fit files). But I forgot to add ses.Records = result.Records that's why ses.Records is null and throw error in JS (there should be no session that has no records).

```sh
@@ -144,6 +144,7 @@ func (s *service) convertListenerResultToActivity(result *ListenerResult) *activ
 
                ses := activity.NewSessionFromLaps(laps, sport)
                ses.Laps = laps
+               ses.Records = result.Records
 
                act.Sessions = append(act.Sessions, ses)
        }
```

I will fix the error by adding the code above, however we still have problem how to handle the anomaly from fit files retrieved from Strava.

**Comment by raditzlawliet** [comment]
> how can this be reproduce? Is this issue persist after refreshing the browser-tab? i tried in my local but it seems fine.

It's continues without refresh after open.
- Open Morning_Ride.fit > Try to edit > Select Trim (But no action)
- (Without refreshing the browser) > Open Morning_Run.fit > Try to edit > Select Trim > Error

**Comment by raditzlawliet** [comment]
> > Open Morning_Run.fit > Try to edit > Trim > error
> 
> I think I know the cause, before we point to the problem, let me explain the full context: In Session, there are Fields: `start_time` and `total_elapsed_time`, these fields are used to group which record is belong to this session. From these fields, we get `EndTime = start_time + total_elapsed_time`, so any `record.Timestamp` between `StartTime` and `EndTime` will be included in this session.
> 
> However, how `total_elapsed_time` in fit files retrieved from Strava is not calculated as we expected, example:
> 
> * Session: start_time: "1056157392",  total_elapsed_time: "2866.0", we get `EndTime = 1056160258`. We expect the last record will have timestamp "1056160258", but we got one record that has "1056160259", so there is one record that's not included in the session. And for records that not included in session, we create new session to accommodate that record (this to accommodate truncated fit files). But I forgot to add ses.Records = result.Records that's why ses.Records is null and throw error in JS (there should be no session that has no records).
> 
> ```shell
> @@ -144,6 +144,7 @@ func (s *service) convertListenerResultToActivity(result *ListenerResult) *activ
>  
>                 ses := activity.NewSessionFromLaps(laps, sport)
>                 ses.Laps = laps
> +               ses.Records = result.Records
>  
>                 act.Sessions = append(act.Sessions, ses)
>         }
> ```
> 
> I will fix the error by adding the code above, however we still have problem how to handle the anomaly from fit files retrieved from Strava.

Since it's anomaly and rare case, i think we can low prio on this case, 
but let take a note (so later we can deal with this)

**Comment by muktihari** [comment]
> Since it's anomaly and rare case, i think we can low prio on this case,
> but let take a note (so later we can deal with this)

The anomaly is for all FIT files from Strava, so I think we need to do something about it but just a quick hack is enough. 
I just push the quick hack for it, if it doesn't catch the anomaly more that the threshold that I set, so be it, we should not accommodate poorly encoded files more than our threshold.

**Comment by muktihari** [comment]
This PR is ready to be reviewed again.

**Comment by raditzlawliet** [comment]
> > Since it's anomaly and rare case, i think we can low prio on this case,
> > but let take a note (so later we can deal with this)
> 
> The anomaly is for all FIT files from Strava, so I think we need to do something about it but just a quick hack is enough. I just push the quick hack for it, if it doesn't catch the anomaly more that the threshold that I set, so be it, we should not accommodate poorly encoded files more than our threshold.

all ? 🤔 okay, let's do quick hack for now.

**Comment by muktihari** [comment]
> all ? 🤔 okay, let's do quick hack for now.

In few files that I retrieve from Strava: yes, the files that written by Strava when we do Record activity directly from the app (not what we upload from xoss or bryton for example). We can retrieve it by go to Strava web -> open activity -> Export Original.

I notice other irregular fit procotol messages being written as well, but since this not affecting our app directly we can ignore.

**Comment by raditzlawliet** [comment]
> Oh wait, I try using one Mat..Loop.fit having 0.01 at start (i think you also already have this file)
This issue is solved on latest, 


> It's continues without refresh after open.
> Open Morning_Ride.fit > Try to edit > Select Trim (But no action)
> (Without refreshing the browser) > Open Morning_Run.fit > Try to edit > Select Trim > Error
while this still occur

**Pull request merged**
