### PR TITLE
fix (#73): handling null altitude, instead of treat as 0, make it minDomain

### PR DESCRIPTION
**Pull request by muktihari**
fix: #73 

image

image

### CODE REVIEW

**Comment by raditzlawliet** [comment]
image
image
there's a undefined records on session didn't check on preprocessor, when using `Morning_Ride/Run.fit`

- this branch `fix/issue-73`
- go mod tidy
- re-build wasm with go 1.20.8
- npm install

**Comment by muktihari** [comment]
The issue you mentioned should be fix by #70, let me merge that PR and update this branch HEAD and see if the problem persist.

**Comment by muktihari** [comment]
So the issue was due to the changes in PR #71, so it's propagate to others. I should have create separate PR to fix it and update all open PR but I put it in #70 😅

**Comment by raditzlawliet** [comment]
🤣 , okay, i tested and works. 
except the snapped things on area graph using mouse, i think not really an issue for now.

**Review by raditzlawliet — APPROVED** [review]

**Comment by muktihari** [comment]
> except the snapped things on area graph using mouse, i think not really an issue for now.

yeah I notice the snapped pointer issue on area graph, I will create new issue regarding this to fix it later.

**Pull request merged**
