### PR TITLE
All Chart Freeze Marker on Pointer Down (unfreeze on pointer down again)

### PR DESCRIPTION
**Pull request by raditzlawliet**
https://github.com/openivity/openivity.github.io/assets/3763178/c9b9d30e-a204-46cf-94aa-cfba781c4335

### CODE REVIEW

**Comment by muktihari** [comment]
Before: respon perfectly fine

https://github.com/openivity/openivity.github.io/assets/15964188/7dcf3cf8-1a1a-46a0-959d-4bba782b1f2c

After: not respon to some touch


https://github.com/openivity/openivity.github.io/assets/15964188/40a11d29-a312-45ef-9ec4-6881738fa61e

Please kindly check, thanks..

**Comment by raditzlawliet** [comment]
> Before: respon perfectly fine
> 
>  RPReplay_Final1700731832.MOV 
> After: not respon to some touch
> 
>  RPReplay_Final1700731866.MOV 
> Please kindly check, thanks..

what device do you use?
which touch did you mean? touch & hold move? or

**Comment by raditzlawliet** [comment]
Newest behavior, you can drag the marker
https://github.com/openivity/openivity.github.io/assets/3763178/5902a20d-2a9d-4782-a8e9-fa8412ce6c06

**Comment by muktihari** [comment]
I tested it using Sony Xperia XZ1 Compact and Iphone 13 mini, the feature is somehow already exist, I mean when I keep scrolling the pointer is still freeze. Now when I try to drag it won't response :(. 

Please test using real mobile devices.

**Comment by raditzlawliet** [comment]
> I tested it using Sony Xperia XZ1 Compact and Iphone 13 mini, the feature is somehow already exist, I mean when I keep scrolling the pointer is still freeze. Now when I try to drag it won't response :(.
> 
> Please test using real mobile devices.

I'm using S21FE with Chrome Browser. Can you record with touch? I'll try on Ipad Mini

**Comment by muktihari** [comment]
lgtm

**Review by muktihari — APPROVED** [review]

**Pull request merged**
