### PR TITLE
Feat: UI Tools Trim & Conceal Connect to Map

### PR DESCRIPTION
**Pull request by raditzlawliet**
- [x] Basic sync Conceal Tool Marker & Selected (with show/hide) with Map
- [x] Basic sync select session with hide/show conceal on map
- [x] Ordering Feature

https://github.com/openivity/openivity.github.io/assets/3763178/9bb1fc26-47fc-4d03-a37a-66ce4eb406c8

### CODE REVIEW

**Comment by raditzlawliet** [comment]
Since Trim & Conceal can selected together, any idea how behavior will show on map?

**Comment by muktihari** [comment]
> Since Trim & Conceal can selected together, any idea how behavior will show on map?

Just show as in the video, but with conceal and trim marker having different color (or different icon or both, up to u)

**Comment by muktihari** [comment]
1. The zIndex of start and dest route icons better be above all marker, it was covered by trim/conceal LineString feature.
image

2. The zIndex conceal/trim marker better be above LineString feature, the conceal icon is covered by trim LineString.
image

3. Can we switch the color between trim and conceal, trim should be look "stronger" or more "firm" than conceal
image

4. Just my personal taste nothing to do with the behaviour: I am not fan of the orange color and the conceal/trim icons, if you don't mind I might change that later 😅

Other than that, everything looks great 👍

**Comment by raditzlawliet** [comment]
Is not done yet, basic functionality is already good enough for now. (we can optimize later)

> 1. The zIndex of start and dest route icons better be above all marker, it was covered by trim/conceal LineString feature.

Of course, All Icon will be above of all route/line.

> 2. The zIndex conceal/trim icons better be above LineString feature, the conceal icon is covered by trim LineString.

since trim/conceal feature using different layer, we can't simply using zIndex. 
But i got your point, Conceal still behind Trim Route, this will do with number 1. 

> 3. Can we switch the color between trim and conceal, trim should be look "stronger" or more "firm" than conceal
> 4. Just my personal taste nothing to do with the behaviour: I am not fan of the orange color and the conceal/trim icons, if you don't mind I might change that later 😅

I'm good with orange, because it reflected "Openivity" title color.
We can change it later, current color are using the reference we discuss on issue.

image
In current theme, Trim use weak color "Light Grey" because it will be gone (Like photoshop crop). 
we can see the "Orange" as "Visible" part and "Dark Grey" as "Conceal" part

**Comment by raditzlawliet** [comment]
image

Yup, i think all basic behavior and functionality is done.

**Comment by muktihari** [comment]
> Is not done yet, basic functionality is already good enough for now. (we can optimize later)

Yes, the functionality is good, I don't see any bug when sliding the slider.

> since trim/conceal feature using different layer, we can't simply using zIndex.
But i got your point, Conceal still behind Trim Route, this will do with number 1.

Ah yes it was also determined by layering order.

> I'm good with orange, because it reflected "Openivity" title color.
We can change it later, current color are using the reference we discuss on issue.

Tbh, I don't want it to look like Strava 😬. Can we keep the previous one? I think the change of color is not part of the issue's scope. We can issue the design change later, we might change it again on the final re-layouting design ,so let's don't bother about what we currently have.

> In current theme, Trim use weak color "Light Grey" because it will be gone.
we can see the "Orange" as "Visible" part and "Dark Grey" as "Conceal" part.

There is a different perspective on this, (disclaimer: there is no right or wrong ya), in my opinion, `trim` is like a cut, something that cut should be sharp, while `conceal` is like just hide something that an overlay should be enough. But we can keep it as now.

**Comment by raditzlawliet** [comment]
> There is a different perspective on this, (disclaimer: there is no right or wrong ya), in my opinion, trim is like a cut, something that cut should be sharp, while conceal is like just hide something that an overlay should be enough. But we can keep it as now.

Do you have any color style idea/ref? 
We can search again in the next issue to have a good style for this.

**Comment by raditzlawliet** [comment]
I think the current color is already "Good" enough and differ the trim/conceal/route.
If you think this "Bad" color (not personal perspective), we can change right now.

If it taste to get great style, we can move on to "find a great style" for this.

**Comment by raditzlawliet** [comment]
> Tbh, I don't want it to look like Strava 😬. Can we keep the previous one? I think the change of color is not part of the issue's scope. We can issue the design change later, we might change it again on the final re-layouting design ,so let's don't bother about what we currently have.

I don't think so, if we keep the previous one, We need to distinct the color right now to avoid confusion. 3 line color with same family (dark gray/ gray/ light gray) can make confusion.

**Comment by raditzlawliet** [comment]
image
how about this one color, i'm not fans of black/dark grey on map route. But i think this pallete is good.

**Comment by muktihari** [comment]
I prefer this:
- `red` (`#e74c3c`)  is like a danger: if you do this, it will be gone
- `green` (`#2ecc71`) is like a safe-zone: in this green area you are safe


image


This is the actual use case when I forgot to turn off device recording, the green is only to show that the color is still distinct than the forest color
image

With color we can remove the points actually, this is what it look like (I can't completely hide the points, the code for applying points are harder to read)
image

**Comment by muktihari** [comment]
> how about this one color, i'm not fans of black/dark grey on map route. But i think this pallete is good.
Route: #161A30
Trim: #31304D
Conceal: #B6BBC4
Outline: White / #F0ECE5

I haven't tried this, let me try first.

**Comment by raditzlawliet** [comment]
Let me clarify: 
- Normal Route: Green `#2ecc71`
- To be trim route: Red ``#f50f30`
- To be concealed route: dark gray `#f15a22`

so the current route will be turn into green

**Comment by raditzlawliet** [comment]
> Route: `#161A30`
> Trim: `#31304D`
> Conceal: `#B6BBC4`
> Outline: White / `#F0ECE5`

image
This kind funny, the trim has similar color with normal route

**Comment by raditzlawliet** [comment]
> Normal Route: dark gray #34495e
> To be trim route: Red #f50f30
> To be concealed route: Green #2ecc71

image
this quite fine, the green one lil mixed with normal route.
normal route, it is still using the previous route color dark gray #34495e 

so i think this one is ok

**Comment by raditzlawliet** [comment]
I'll hide the icon, but the code still there. so we can change it later.

**Comment by muktihari** [comment]
I just open a file and the trim/conceal icons are showing unexpectedly

Screen Shot 2023-12-21 at 08 40 08

**Comment by muktihari** [comment]
> I'll hide the icon, but the code still there. so we can change it later.

Sure, I'll help finding icons later.

**Comment by muktihari** [comment]
Suggestion on icons? I can change the color.

image

image

image

image

**Comment by raditzlawliet** [comment]
The 1st, 2nd and 4th looks good. can you attach all the svg? i'll put it

**Comment by muktihari** [comment]
> The 1st, 2nd and 4th looks good. can you attach all the svg? i'll put it

Sure, here it is [icons.zip](https://github.com/openivity/openivity.github.io/files/13736578/icons.zip)

**Comment by raditzlawliet** [comment]
Fig. Example 1
image

Fig. Example 2
image

Fig. Example 4
image

**Comment by raditzlawliet** [comment]
Number 1 & 4 is good, i'll apply 4 first

**Comment by raditzlawliet** [comment]
try colored: 
image
image
The red+white is also good, but the green+white/black not good enough.

**Comment by muktihari** [comment]
I personally prefer the black one, more clean and elegant. 

image

**Comment by muktihari** [comment]
Btw the blue circle is still show up. I just open the file without going to Tools section.

image

**Comment by raditzlawliet** [comment]
as we agree to use the black or 4th, let conclude it.

**Comment by raditzlawliet** [comment]
> Btw the blue circle is still show up. I just open the file without going to Tools section.
> 
> image

not sure, what blue circle is.
not showing up in my side

**Comment by muktihari** [comment]
> not sure, what blue circle is.
not showing up in my side

It only show when the page is refreshed (or a new page), then open a file, it will show both in chrome and firefox. The second file we open it's gone. Let me help investigate.

**Comment by raditzlawliet** [comment]
thanks for provide, i'll check it first

**Comment by raditzlawliet** [comment]
I found it's relate with undefined style on point feature. fix on next commit

**Comment by muktihari** [comment]
I confirm it's gone
image

> as we agree to use the black or 4th, let conclude it.

Ok, let's change this to black, it's still showing red-green icon now

image

**Comment by muktihari** [comment]
After change the icon to the black (or the 4th), you can merge this PR. lgtm.

**Pull request merged**
