### PR TITLE
perf(no-ticket): reduce interop bottleneck

### PR DESCRIPTION
**Pull request by muktihari**
Previously, we used `map[string]any` for a simple reason: it's a type that `syscall/js` accept without doing much work. However, this introduce performance bottlenecks:
1. Since we use map, Go will create internal allocation for the map itself to work. And the time spent to create the map is also take part on adding bottleneck.
1. There are a lot things going on in `syscall/js ValueOf`, not only it uses reflection, but also recursive function calls.

To reduce time spent on serialization and interop between wasm and js, I propose new way of doing serialization, manual marshal json without reflection. This not only that `string` is a type that `syscall/js` accept as well, it doesn't produce bottleneck as in previous serialization and this doesn't bring much complexity, the code is still fairly readable.

For the experiment, decoding a FIT file of a **_194 km long ride with more than 33k records_**, that previously took around **2000ms** to complete, now it took only around **1000ms**, half of the previous one, 100% faster  🚀.

<- Previous | After -> 
image image

`syscall/js ValueOf` ref: 
image

### CODE REVIEW

**Comment by muktihari** [comment]
Btw, I forgot to commit `activity-service.ts` in earlier commit, making the previous commit can not be tested, will throw error in FE, my bad 😅

Now, I come with new updates. It becomes a little bit faster 🚀
Screen Shot 2023-12-20 at 12 01 37


What did I do:
1. Remove strings concatenation
from this
```go
// runtime make new string each time this is called before writing to buf
buf.WriteString("\"positionLat\":" + strconv.FormatFloat(*r.PositionLat, 'g', -1, 64) + ",")
```
changed into

```go
buf.WriteString("\"positionLong\":") // this will be treated as a string constant by the compiler
buf.WriteString(strconv.FormatFloat(*r.PositionLong, 'g', -1, 64)) // the only string we create
buf.WriteByte(',') // this is also a constant byte
```

2. Use sync.Pool for *bytes.Buffer instead of creating new each time we marshal a struct, with this we only need 3 *bytes.Buffer (1 for Activity, 1 for Session, 1 reusable by Lap and Record). 

    Previously we create `*bytes.Buffer` as much as we have the data, if we have 33k record then we need 33k `*bytes.Buffer` to marshal those records, possible making runtime GC busy.

**Comment by muktihari** [comment]
This is ready to be review ya @raditzlawliet. 

Btw I want to know the performance in your machine, since mine is an old 2015 machine with older browser. I bet it will be faster in your new machine. For comparison we can use **11. Sembalun (End).fit**


<- Before (openivity.github.io) | After (localhost)
image  image

**Comment by raditzlawliet** [comment]
Before (`dev`)
image

After
image
image

Overall looks great 👍

**Comment by muktihari** [comment]
Wow, there is around 200ms different between out machine, lol. 

Ok concluded, will merge this.

**Review by raditzlawliet — APPROVED** [review]
This is wild, since it manually marshal to json.
I just try with normal files (like other language or other hardware/sensor).

Just a note for us in the future to more carefully checking on this 😆

**Pull request merged**
