### PR TITLE
fix: simplify and ensure correctness of data aggregation

### PR DESCRIPTION
**Pull request by muktihari**
Instead of manually aggregating Lap and Session structs per field basis where the number of fields to be accommodated is unlimited, let's use reflection to do the job, this way we don't lose any data and our code become simpler. The aggregator code is copied from https://github.com/muktihari/fit/blob/master/cmd/fitactivity/aggregator/aggregator.go with some modifications to accommodate our needs.

The use of reflection is minimal as the number of laps and sessions to aggregate is small, it's fast enough to run in WebAssembly.

### CODE REVIEW

**Comment by raditzlawliet** [comment]
Is there an example of the problem case and the solved result with this PR?

**Comment by muktihari** [comment]
> Is there an example of the problem case and the solved result with this PR?

Please take a look at  the structure of the session message first: 
https://github.com/muktihari/fit/blob/master/profile/mesgdef/session_gen.go. 

There are so many fields that need to be aggregated, previously we were only calculateing around 22 out of 155 fields (14%). While not all fields will be present since some fields are sport specific, we are certainly missing some fields.

For instance, some manufacturers such as Garmin prefer using fields start with "Enhanced" prefix (EnhancedAvgSpeed, EnhancedMaxSpeed, EnhancedAvgAltitude, etc). We were not able to aggregate those field, resulting data loss.

**Comment by muktihari** [comment]
This PR relate with #113 . This PR handle the data aggregation (Lap and Session), where #113 handles preprocessing Record and data presentation (marshaling into json that will be consumed by FE). If you want file to test, you can use https://github.com/roznet/fit-benchmarks/blob/main/large.fit

**Comment by muktihari** [comment]
I just share you a gdrive folder containing sample FIT files that you can test ya @raditzlawliet

**Comment by muktihari** [comment]
I bump the sdk to v0.21.5 to address this issue: https://github.com/muktihari/fit/issues/397

**Comment by muktihari** [comment]
Close due to #114

**Comment by muktihari** [comment]
Reopened due  #114 is postponed

**Pull request merged**
